services:
    mailpit-nginx:
        container_name: mailpit-nginx
        image: nginx:${NGINX_VERSION}
        restart: unless-stopped
        volumes:
            - ./docker/nginx/${VHOST_FILE}:/etc/nginx/conf.d/custom.conf
        ports:
            - "80"
        depends_on:
            - mailpit-mail
        environment:
            VIRTUAL_HOST: ${DOMAIN_HOST}
            SELF_SIGNED_HOST: ${SELF_SIGNED_HOST}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: ${DOMAIN_HOST}
            LETSENCRYPT_EMAIL: ${DOMAIN_EMAIL}
        networks:
            - nginx-proxy
            - mailpit

    mailpit-mail:
        container_name: mailpit-mail
        image: axllent/mailpit:${MAILPIT_VERSION}
        restart: unless-stopped
        environment:
            MP_MAX_MESSAGES: 5000
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        ports:
            - ${MAILPIT_PORT}:1025
        networks:
            - mailpit

networks:
    mailpit:
    nginx-proxy:
        external: true
